name: Build, Push, and Deploy

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-push-functions:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        function: [create-job, download-job, get-job-status, process-job]
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to OCI Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ secrets.REGION }}.ocir.io
          username: ${{ secrets.TENANCY_NAMESPACE }}/${{ secrets.OCIR_USER }}
          password: ${{ secrets.OCIR_AUTH_TOKEN }}

      - name: Build and Push Docker Image
        run: |
          IMAGE_NAME="${{ secrets.REGION }}.ocir.io/${{ secrets.TENANCY_NAMESPACE }}/${{ secrets.REPO_NAME }}:${{ matrix.function }}-${{ github.sha }}"
          
          docker build \
            --build-arg FUNCTION_NAME=${{ matrix.function }} \
            -t ${IMAGE_NAME} \
            -f ./functions/${{ matrix.function }}/Dockerfile .
            
          docker push ${IMAGE_NAME}
          
          echo "Successfully pushed ${{ matrix.function }} to ${IMAGE_NAME}"

  deploy-frontend:
    runs-on: ubuntu-latest
    needs: build-and-push-functions
    
    # Set credentials as environment variables for the entire job
    env:
      OCI_CLI_USER: ${{ secrets.OCI_USER_OCID }}
      OCI_CLI_TENANCY: ${{ secrets.OCI_TENANCY_OCID }}
      OCI_CLI_FINGERPRINT: ${{ secrets.OCI_FINGERPRINT }}
      OCI_CLI_KEY_CONTENT: ${{ secrets.OCI_PRIVATE_KEY }}
      OCI_CLI_REGION: ${{ secrets.OCI_REGION }}
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # This single step now handles authentication and execution
      - name: Deploy Frontend to Object Storage
        uses: oracle-actions/run-oci-cli-command@v1.3.2
        with:
          command: |
            oci os object put \
              --namespace ${{ secrets.TENANCY_NAMESPACE }} \
              --bucket-name doc-converter-frontend \
              --file frontend/index.html \
              --name index.html \
              --force
        
      - name: Confirm Deployment
        run: echo "Frontend successfully deployed to OCI Object Storage."